name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Build
      run: npm install
    - name: Fetch latest data
      run: |-
        npm run action | jq -r '.[] | [.date,.time,.sequenceNum,.incidentNature,.location] | @csv' | cat - data/reports.csv | awk '!x[$0]++' > temp.csv
        mv temp.csv data/reports.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
