name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Build
      run: npm install
    - name: Fetch latest data
      run: |-
        curl https://www.co.thurston.wa.us/apps/sheriff-911-calls/calls.csv > calls.csv
        iconv -c -f utf-16le calls.csv > calls-utf8.csv
        tail +2 calls-utf8.csv | cat data/reports.csv - > temp.csv
        mv temp.csv data/reports.csv
        rm calls.csv calls-utf8.csv
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
